name: flowrl
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - glew=2.1.0=h9c3ff4c_2
  - kernel-headers_linux-64=2.6.32=he073ed8_17
  - ld_impl_linux-64=2.40=h12ee557_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libdrm-cos6-x86_64=2.4.65=h9b0a68f_1105
  - libegl=1.7.0=ha4b6fd6_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgl=1.7.0=ha4b6fd6_2
  - libglu=9.0.3=h03adeef_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_2
  - libpciaccess=0.18=hd590300_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libx11-common-cos6-x86_64=1.6.4=h9b0a68f_1105
  - libx11-cos6-x86_64=1.6.4=h9b0a68f_1105
  - libxcb=1.17.0=h8a09558_0
  - mesa-dri-drivers-cos6-x86_64=11.0.7=h9b0a68f_1105
  - mesa-dri1-drivers-cos6-x86_64=7.11=h9b0a68f_1105
  - mesa-libgl-cos6-x86_64=11.0.7=h9b0a68f_1105
  - ncurses=6.4=h6a678d5_0
  - openssl=3.5.0=h7b32b05_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - python=3.9.21=he870216_1
  - readline=8.2=h5eee18b_0
  - sqlite=3.45.3=h5eee18b_0
  - sysroot_linux-64=2.12=he073ed8_17
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.2.2
      - annotated-types==0.7.0
      - asttokens==3.0.0
      - boto3==1.38.27
      - botocore==1.38.27
      - certifi==2025.4.26
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - chex==0.1.89
      - click==8.1.8
      - cloudpickle==3.1.1
      - contextlib2==21.6.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - cython==3.1.1
      - d4rl==1.1
      - decorator==5.2.1
      - distrax==0.1.5
      - dm-control==1.0.30
      - dm-env==1.6
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - etils==1.5.2
      - eval-type-backport==0.2.2
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - farama-notifications==0.0.4
      - fasteners==0.19
      - flax==0.8.5
      - fonttools==4.58.0
      - fsspec==2025.3.2
      - gast==0.6.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - glfw==2.9.0
      - gym==0.23.1
      - gym-notices==0.0.8
      - gymnasium==0.29.1
      - h5py==3.13.0
      - humanize==4.12.3
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - ipython==8.18.1
      - jax==0.4.30
      - jax-cuda12-pjrt==0.4.30
      - jax-cuda12-plugin==0.4.30
      - jaxlib==0.4.30
      - jedi==0.19.2
      - jmespath==1.0.1
      - kiwisolver==1.4.7
      - labmaze==1.0.6
      - lxml==5.4.0
      - markdown-it-py==3.0.0
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mjrl==1.0.0
      - ml-collections==0.1.1
      - ml-dtypes==0.5.1
      - moviepy==2.1.2
      - msgpack==1.1.0
      - mujoco==3.3.2
      - mujoco-py==2.1.2.14
      - nest-asyncio==1.6.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.9.0.13
      - nvidia-cuda-cupti-cu12==12.9.19
      - nvidia-cuda-nvcc-cu12==12.9.41
      - nvidia-cuda-runtime-cu12==12.9.37
      - nvidia-cudnn-cu12==9.10.0.56
      - nvidia-cufft-cu12==11.4.0.6
      - nvidia-cusolver-cu12==11.7.4.40
      - nvidia-cusparse-cu12==12.5.9.5
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu12==2.26.5
      - nvidia-nvjitlink-cu12==12.9.41
      - nvitop==1.5.0
      - ogbench==1.1.0
      - opt-einsum==3.4.0
      - optax==0.2.4
      - orbax-checkpoint==0.6.4
      - packaging==25.0
      - pandas==2.2.3
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==10.4.0
      - pip==25.1.1
      - platformdirs==4.3.8
      - proglog==0.1.12
      - prompt-toolkit==3.0.51
      - protobuf==6.31.0
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pybullet==3.2.7
      - pycparser==2.22
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pygments==2.19.1
      - pynvml==12.0.0
      - pyopengl==3.1.9
      - pyopengl-accelerate==3.1.9
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - pytz==2025.2
      - pyvirtualdisplay==3.0
      - pyyaml==6.0.2
      - requests==2.32.3
      - rich==14.0.0
      - s3transfer==0.13.0
      - scipy==1.13.1
      - sentry-sdk==2.28.0
      - setproctitle==1.3.6
      - setuptools==80.8.0
      - shimmy==0.2.1
      - six==1.17.0
      - smmap==5.0.2
      - stack-data==0.6.3
      - swankit==0.1.8
      - swanlab==0.5.9
      - tensorflow-probability==0.25.0
      - tensorstore==0.1.69
      - termcolor==3.1.0
      - toolz==1.0.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.13.2
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - urllib3==1.26.20
      - wandb==0.19.11
      - wcwidth==0.2.13
      - zipp==3.21.0
prefix: /opt/conda/envs/flowrl
